# Generated by Django 3.0.2 on 2020-11-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
