# Generated by Django 3.0.2 on 2020-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
